---
booktitle: Proceedings of the 24th Annual Conference on Learning Theory
publisher: JMLR Workshop and Conference Proceedings
volume: 19
month: 0
year: '2011'
start: 2011-06-09
end: 2011-06-11
published: 2011-12-21
shortname: COLT
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: KakadeCOLT2011
cycles: false
editor:
- given: Sham M.
  family: Kakade
- given: Ulrike
  family: von Luxburg
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 24th Annual Conference on Learning Theory
    Held in Budapest, Hungary on 09-11 June 2011

  Published as Volume 19 by the Proceedings of Machine Learning Research on 21 December 2011.

  Volume Edited by:
    Sham M. Kakade
    Ulrike von Luxburg

  Series Editors:
    Neil D. Lawrence
date_str: '09--11 Jun'
url: http://proceedings.mlr.press
baseurl: "/v19"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v19
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Proceedings of the 24th Annual Conference on Learning Theory
  url: 
  location: Budapest, Hungary
  dates:
  - 2011-06-09
  - 2011-06-10
  - 2011-06-11
  number: 24
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
