---
booktitle: Proceedings of the 24th Annual Conference on Learning Theory
publisher: JMLR Workshop and Conference Proceedings
volume: 19
month: 0
year: '2011'
start: 2011-06-09
end: 2011-06-11
published: 2011-12-21
shortname: COLT
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: KakadeCOLT2011
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Sham M.
  family: Kakade
- given: Ulrike
  family: von Luxburg
description: |
  Proceedings of the 24th Annual Conference on Learning Theory
    Held in Budapest, Hungary on 09-11 June 2011

  Published as Volume 19 by the Proceedings of Machine Learning Research on 21 December 2011.

  Volume Edited by:
    Sham M. Kakade
    Ulrike von Luxburg

  Series Editors:
    Neil D. Lawrence
date_str: 09--11 Jun
url: http://proceedings.mlr.press
baseurl: "/v19"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v19
bibtex_copy: true
email: ''
conference:
  name: Proceedings of the 24th Annual Conference on Learning Theory
  url: 
  location: Budapest, Hungary
  dates:
  - 2011-06-09
  - 2011-06-10
  - 2011-06-11
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v19.bib
