---
booktitle: Proceedings of the 24th Annual Conference on Learning Theory
publisher: JMLR Workshop and Conference Proceedings
volume: 19
month: 0
year: '2011'
start: 2011-06-09
end: 2011-06-11
published: 2011-12-21
shortname: COLT
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: KakadeCOLT2011
abstract: ''
editor:
- given: Sham M.
  family: Kakade
- given: Ulrike
  family: von Luxburg
title: Proceedings of the 24th Annual Conference on Learning Theory
email: ''
description: Proceedings of the 24th Annual Conference on Learning Theory, Budapest,
  Hungary
url: http://proceedings.mlr.press
baseurl: "/v19"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v19
conference:
  name: Proceedings of the 24th Annual Conference on Learning Theory
  url: 
  location: Budapest, Hungary
  dates:
  - 2011-06-09
  - 2011-06-10
  - 2011-06-11
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v19.bib
